apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
rules:
- apiGroups: ["db.buffalo.com"]
  resources: ["sqlcow"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["db.buffalo.com"]
  resources: ["sqlcow/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]  # Новое правило для отслеживания подов
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
