apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
  namespace: man-khao-system
spec:
  serviceName: mssql-service
  replicas: 1  # Масштабирование
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "KorovaIvanovna12!"
        ports:
        - containerPort: 1433
          name: mssql
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql
        - name: mssql-cow-mount
          mountPath: /cow
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
      volumes:
      - name: mssql-cow-mount
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: mssql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
spec:
  ports:
  - port: 1433
    targetPort: 1433
  selector:
    app: mssql
  clusterIP: None