# permissions for end users to view mssqldatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: man-khao
    app.kubernetes.io/managed-by: kustomize
  name: mssqldatabase-viewer-role
rules:
- apiGroups:
  - db.buffalo.com
  resources:
  - mssqldatabases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db.buffalo.com
  resources:
  - mssqldatabases/status
  verbs:
  - get
