# permissions for end users to edit mssqldatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: man-khao
    app.kubernetes.io/managed-by: kustomize
  name: mssqldatabase-editor-role
rules:
- apiGroups:
  - db.buffalo.com
  resources:
  - mssqldatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.buffalo.com
  resources:
  - mssqldatabases/status
  verbs:
  - get
